<?php 

/**
 * @file
 * Loads data array for Smallword lat/long lookups
 * Lat / Long data from: https://developers.google.com/public-data/docs/canonical/countries_csv
 */

global $smallworld_lookup; 

$smallworld_lookup = array (
  'AD' => 
  array (
    'lat' => '42.546245',
    'long' => '1.601554',
    'name' => 'Andorra',
  ),
  'AE' => 
  array (
    'lat' => '23.424076',
    'long' => '53.847818',
    'name' => 'United Arab Emirates',
  ),
  'AF' => 
  array (
    'lat' => '33.93911',
    'long' => '67.709953',
    'name' => 'Afghanistan',
  ),
  'AG' => 
  array (
    'lat' => '17.060816',
    'long' => '-61.796428',
    'name' => 'Antigua and Barbuda',
  ),
  'AI' => 
  array (
    'lat' => '18.220554',
    'long' => '-63.068615',
    'name' => 'Anguilla',
  ),
  'AL' => 
  array (
    'lat' => '41.153332',
    'long' => '20.168331',
    'name' => 'Albania',
  ),
  'AM' => 
  array (
    'lat' => '40.069099',
    'long' => '45.038189',
    'name' => 'Armenia',
  ),
  'AN' => 
  array (
    'lat' => '12.226079',
    'long' => '-69.060087',
    'name' => 'Netherlands Antilles',
  ),
  'AO' => 
  array (
    'lat' => '-11.202692',
    'long' => '17.873887',
    'name' => 'Angola',
  ),
  'AQ' => 
  array (
    'lat' => '-75.250973',
    'long' => '-0.071389',
    'name' => 'Antarctica',
  ),
  'AR' => 
  array (
    'lat' => '-38.416097',
    'long' => '-63.616672',
    'name' => 'Argentina',
  ),
  'AS' => 
  array (
    'lat' => '-14.270972',
    'long' => '-170.132217',
    'name' => 'American Samoa',
  ),
  'AT' => 
  array (
    'lat' => '47.516231',
    'long' => '14.550072',
    'name' => 'Austria',
  ),
  'AU' => 
  array (
    'lat' => '-25.274398',
    'long' => '133.775136',
    'name' => 'Australia',
  ),
  'AW' => 
  array (
    'lat' => '12.52111',
    'long' => '-69.968338',
    'name' => 'Aruba',
  ),
  'AZ' => 
  array (
    'lat' => '40.143105',
    'long' => '47.576927',
    'name' => 'Azerbaijan',
  ),
  'BA' => 
  array (
    'lat' => '43.915886',
    'long' => '17.679076',
    'name' => 'Bosnia and Herzegovina',
  ),
  'BB' => 
  array (
    'lat' => '13.193887',
    'long' => '-59.543198',
    'name' => 'Barbados',
  ),
  'BD' => 
  array (
    'lat' => '23.684994',
    'long' => '90.356331',
    'name' => 'Bangladesh',
  ),
  'BE' => 
  array (
    'lat' => '50.503887',
    'long' => '4.469936',
    'name' => 'Belgium',
  ),
  'BF' => 
  array (
    'lat' => '12.238333',
    'long' => '-1.561593',
    'name' => 'Burkina Faso',
  ),
  'BG' => 
  array (
    'lat' => '42.733883',
    'long' => '25.48583',
    'name' => 'Bulgaria',
  ),
  'BH' => 
  array (
    'lat' => '25.930414',
    'long' => '50.637772',
    'name' => 'Bahrain',
  ),
  'BI' => 
  array (
    'lat' => '-3.373056',
    'long' => '29.918886',
    'name' => 'Burundi',
  ),
  'BJ' => 
  array (
    'lat' => '9.30769',
    'long' => '2.315834',
    'name' => 'Benin',
  ),
  'BM' => 
  array (
    'lat' => '32.321384',
    'long' => '-64.75737',
    'name' => 'Bermuda',
  ),
  'BN' => 
  array (
    'lat' => '4.535277',
    'long' => '114.727669',
    'name' => 'Brunei',
  ),
  'BO' => 
  array (
    'lat' => '-16.290154',
    'long' => '-63.588653',
    'name' => 'Bolivia',
  ),
  'BR' => 
  array (
    'lat' => '-14.235004',
    'long' => '-51.92528',
    'name' => 'Brazil',
  ),
  'BS' => 
  array (
    'lat' => '25.03428',
    'long' => '-77.39628',
    'name' => 'Bahamas',
  ),
  'BT' => 
  array (
    'lat' => '27.514162',
    'long' => '90.433601',
    'name' => 'Bhutan',
  ),
  'BV' => 
  array (
    'lat' => '-54.423199',
    'long' => '3.413194',
    'name' => 'Bouvet Island',
  ),
  'BW' => 
  array (
    'lat' => '-22.328474',
    'long' => '24.684866',
    'name' => 'Botswana',
  ),
  'BY' => 
  array (
    'lat' => '53.709807',
    'long' => '27.953389',
    'name' => 'Belarus',
  ),
  'BZ' => 
  array (
    'lat' => '17.189877',
    'long' => '-88.49765',
    'name' => 'Belize',
  ),
  'CA' => 
  array (
    'lat' => '56.130366',
    'long' => '-106.346771',
    'name' => 'Canada',
  ),
  'CC' => 
  array (
    'lat' => '-12.164165',
    'long' => '96.870956',
    'name' => 'Cocos [Keeling] Islands',
  ),
  'CD' => 
  array (
    'lat' => '-4.038333',
    'long' => '21.758664',
    'name' => 'Congo [DRC]',
  ),
  'CF' => 
  array (
    'lat' => '6.611111',
    'long' => '20.939444',
    'name' => 'Central African Republic',
  ),
  'CG' => 
  array (
    'lat' => '-0.228021',
    'long' => '15.827659',
    'name' => 'Congo [Republic]',
  ),
  'CH' => 
  array (
    'lat' => '46.818188',
    'long' => '8.227512',
    'name' => 'Switzerland',
  ),
  'CI' => 
  array (
    'lat' => '7.539989',
    'long' => '-5.54708',
    'name' => 'Côte d\'Ivoire',
  ),
  'CK' => 
  array (
    'lat' => '-21.236736',
    'long' => '-159.777671',
    'name' => 'Cook Islands',
  ),
  'CL' => 
  array (
    'lat' => '-35.675147',
    'long' => '-71.542969',
    'name' => 'Chile',
  ),
  'CM' => 
  array (
    'lat' => '7.369722',
    'long' => '12.354722',
    'name' => 'Cameroon',
  ),
  'CN' => 
  array (
    'lat' => '35.86166',
    'long' => '104.195397',
    'name' => 'China',
  ),
  'CO' => 
  array (
    'lat' => '4.570868',
    'long' => '-74.297333',
    'name' => 'Colombia',
  ),
  'CR' => 
  array (
    'lat' => '9.748917',
    'long' => '-83.753428',
    'name' => 'Costa Rica',
  ),
  'CU' => 
  array (
    'lat' => '21.521757',
    'long' => '-77.781167',
    'name' => 'Cuba',
  ),
  'CV' => 
  array (
    'lat' => '16.002082',
    'long' => '-24.013197',
    'name' => 'Cape Verde',
  ),
  'CX' => 
  array (
    'lat' => '-10.447525',
    'long' => '105.690449',
    'name' => 'Christmas Island',
  ),
  'CY' => 
  array (
    'lat' => '35.126413',
    'long' => '33.429859',
    'name' => 'Cyprus',
  ),
  'CZ' => 
  array (
    'lat' => '49.817492',
    'long' => '15.472962',
    'name' => 'Czech Republic',
  ),
  'DE' => 
  array (
    'lat' => '51.165691',
    'long' => '10.451526',
    'name' => 'Germany',
  ),
  'DJ' => 
  array (
    'lat' => '11.825138',
    'long' => '42.590275',
    'name' => 'Djibouti',
  ),
  'DK' => 
  array (
    'lat' => '56.26392',
    'long' => '9.501785',
    'name' => 'Denmark',
  ),
  'DM' => 
  array (
    'lat' => '15.414999',
    'long' => '-61.370976',
    'name' => 'Dominica',
  ),
  'DO' => 
  array (
    'lat' => '18.735693',
    'long' => '-70.162651',
    'name' => 'Dominican Republic',
  ),
  'DZ' => 
  array (
    'lat' => '28.033886',
    'long' => '1.659626',
    'name' => 'Algeria',
  ),
  'EC' => 
  array (
    'lat' => '-1.831239',
    'long' => '-78.183406',
    'name' => 'Ecuador',
  ),
  'EE' => 
  array (
    'lat' => '58.595272',
    'long' => '25.013607',
    'name' => 'Estonia',
  ),
  'EG' => 
  array (
    'lat' => '26.820553',
    'long' => '30.802498',
    'name' => 'Egypt',
  ),
  'EH' => 
  array (
    'lat' => '24.215527',
    'long' => '-12.885834',
    'name' => 'Western Sahara',
  ),
  'ER' => 
  array (
    'lat' => '15.179384',
    'long' => '39.782334',
    'name' => 'Eritrea',
  ),
  'ES' => 
  array (
    'lat' => '40.463667',
    'long' => '-3.74922',
    'name' => 'Spain',
  ),
  'ET' => 
  array (
    'lat' => '9.145',
    'long' => '40.489673',
    'name' => 'Ethiopia',
  ),
  'FI' => 
  array (
    'lat' => '61.92411',
    'long' => '25.748151',
    'name' => 'Finland',
  ),
  'FJ' => 
  array (
    'lat' => '-16.578193',
    'long' => '179.414413',
    'name' => 'Fiji',
  ),
  'FK' => 
  array (
    'lat' => '-51.796253',
    'long' => '-59.523613',
    'name' => 'Falkland Islands [Islas Malvinas]',
  ),
  'FM' => 
  array (
    'lat' => '7.425554',
    'long' => '150.550812',
    'name' => 'Micronesia',
  ),
  'FO' => 
  array (
    'lat' => '61.892635',
    'long' => '-6.911806',
    'name' => 'Faroe Islands',
  ),
  'FR' => 
  array (
    'lat' => '46.227638',
    'long' => '2.213749',
    'name' => 'France',
  ),
  'GA' => 
  array (
    'lat' => '-0.803689',
    'long' => '11.609444',
    'name' => 'Gabon',
  ),
  'GB' => 
  array (
    'lat' => '55.378051',
    'long' => '-3.435973',
    'name' => 'United Kingdom',
  ),
  'GD' => 
  array (
    'lat' => '12.262776',
    'long' => '-61.604171',
    'name' => 'Grenada',
  ),
  'GE' => 
  array (
    'lat' => '42.315407',
    'long' => '43.356892',
    'name' => 'Georgia',
  ),
  'GF' => 
  array (
    'lat' => '3.933889',
    'long' => '-53.125782',
    'name' => 'French Guiana',
  ),
  'GG' => 
  array (
    'lat' => '49.465691',
    'long' => '-2.585278',
    'name' => 'Guernsey',
  ),
  'GH' => 
  array (
    'lat' => '7.946527',
    'long' => '-1.023194',
    'name' => 'Ghana',
  ),
  'GI' => 
  array (
    'lat' => '36.137741',
    'long' => '-5.345374',
    'name' => 'Gibraltar',
  ),
  'GL' => 
  array (
    'lat' => '71.706936',
    'long' => '-42.604303',
    'name' => 'Greenland',
  ),
  'GM' => 
  array (
    'lat' => '13.443182',
    'long' => '-15.310139',
    'name' => 'Gambia',
  ),
  'GN' => 
  array (
    'lat' => '9.945587',
    'long' => '-9.696645',
    'name' => 'Guinea',
  ),
  'GP' => 
  array (
    'lat' => '16.995971',
    'long' => '-62.067641',
    'name' => 'Guadeloupe',
  ),
  'GQ' => 
  array (
    'lat' => '1.650801',
    'long' => '10.267895',
    'name' => 'Equatorial Guinea',
  ),
  'GR' => 
  array (
    'lat' => '39.074208',
    'long' => '21.824312',
    'name' => 'Greece',
  ),
  'GS' => 
  array (
    'lat' => '-54.429579',
    'long' => '-36.587909',
    'name' => 'South Georgia and the South Sandwich Islands',
  ),
  'GT' => 
  array (
    'lat' => '15.783471',
    'long' => '-90.230759',
    'name' => 'Guatemala',
  ),
  'GU' => 
  array (
    'lat' => '13.444304',
    'long' => '144.793731',
    'name' => 'Guam',
  ),
  'GW' => 
  array (
    'lat' => '11.803749',
    'long' => '-15.180413',
    'name' => 'Guinea-Bissau',
  ),
  'GY' => 
  array (
    'lat' => '4.860416',
    'long' => '-58.93018',
    'name' => 'Guyana',
  ),
  'GZ' => 
  array (
    'lat' => '31.354676',
    'long' => '34.308825',
    'name' => 'Gaza Strip',
  ),
  'HK' => 
  array (
    'lat' => '22.396428',
    'long' => '114.109497',
    'name' => 'Hong Kong',
  ),
  'HM' => 
  array (
    'lat' => '-53.08181',
    'long' => '73.504158',
    'name' => 'Heard Island and McDonald Islands',
  ),
  'HN' => 
  array (
    'lat' => '15.199999',
    'long' => '-86.241905',
    'name' => 'Honduras',
  ),
  'HR' => 
  array (
    'lat' => '45.1',
    'long' => '15.2',
    'name' => 'Croatia',
  ),
  'HT' => 
  array (
    'lat' => '18.971187',
    'long' => '-72.285215',
    'name' => 'Haiti',
  ),
  'HU' => 
  array (
    'lat' => '47.162494',
    'long' => '19.503304',
    'name' => 'Hungary',
  ),
  'ID' => 
  array (
    'lat' => '-0.789275',
    'long' => '113.921327',
    'name' => 'Indonesia',
  ),
  'IE' => 
  array (
    'lat' => '53.41291',
    'long' => '-8.24389',
    'name' => 'Ireland',
  ),
  'IL' => 
  array (
    'lat' => '31.046051',
    'long' => '34.851612',
    'name' => 'Israel',
  ),
  'IM' => 
  array (
    'lat' => '54.236107',
    'long' => '-4.548056',
    'name' => 'Isle of Man',
  ),
  'IN' => 
  array (
    'lat' => '20.593684',
    'long' => '78.96288',
    'name' => 'India',
  ),
  'IO' => 
  array (
    'lat' => '-6.343194',
    'long' => '71.876519',
    'name' => 'British Indian Ocean Territory',
  ),
  'IQ' => 
  array (
    'lat' => '33.223191',
    'long' => '43.679291',
    'name' => 'Iraq',
  ),
  'IR' => 
  array (
    'lat' => '32.427908',
    'long' => '53.688046',
    'name' => 'Iran',
  ),
  'IS' => 
  array (
    'lat' => '64.963051',
    'long' => '-19.020835',
    'name' => 'Iceland',
  ),
  'IT' => 
  array (
    'lat' => '41.87194',
    'long' => '12.56738',
    'name' => 'Italy',
  ),
  'JE' => 
  array (
    'lat' => '49.214439',
    'long' => '-2.13125',
    'name' => 'Jersey',
  ),
  'JM' => 
  array (
    'lat' => '18.109581',
    'long' => '-77.297508',
    'name' => 'Jamaica',
  ),
  'JO' => 
  array (
    'lat' => '30.585164',
    'long' => '36.238414',
    'name' => 'Jordan',
  ),
  'JP' => 
  array (
    'lat' => '36.204824',
    'long' => '138.252924',
    'name' => 'Japan',
  ),
  'KE' => 
  array (
    'lat' => '-0.023559',
    'long' => '37.906193',
    'name' => 'Kenya',
  ),
  'KG' => 
  array (
    'lat' => '41.20438',
    'long' => '74.766098',
    'name' => 'Kyrgyzstan',
  ),
  'KH' => 
  array (
    'lat' => '12.565679',
    'long' => '104.990963',
    'name' => 'Cambodia',
  ),
  'KI' => 
  array (
    'lat' => '-3.370417',
    'long' => '-168.734039',
    'name' => 'Kiribati',
  ),
  'KM' => 
  array (
    'lat' => '-11.875001',
    'long' => '43.872219',
    'name' => 'Comoros',
  ),
  'KN' => 
  array (
    'lat' => '17.357822',
    'long' => '-62.782998',
    'name' => 'Saint Kitts and Nevis',
  ),
  'KP' => 
  array (
    'lat' => '40.339852',
    'long' => '127.510093',
    'name' => 'North Korea',
  ),
  'KR' => 
  array (
    'lat' => '35.907757',
    'long' => '127.766922',
    'name' => 'South Korea',
  ),
  'KW' => 
  array (
    'lat' => '29.31166',
    'long' => '47.481766',
    'name' => 'Kuwait',
  ),
  'KY' => 
  array (
    'lat' => '19.513469',
    'long' => '-80.566956',
    'name' => 'Cayman Islands',
  ),
  'KZ' => 
  array (
    'lat' => '48.019573',
    'long' => '66.923684',
    'name' => 'Kazakhstan',
  ),
  'LA' => 
  array (
    'lat' => '19.85627',
    'long' => '102.495496',
    'name' => 'Laos',
  ),
  'LB' => 
  array (
    'lat' => '33.854721',
    'long' => '35.862285',
    'name' => 'Lebanon',
  ),
  'LC' => 
  array (
    'lat' => '13.909444',
    'long' => '-60.978893',
    'name' => 'Saint Lucia',
  ),
  'LI' => 
  array (
    'lat' => '47.166',
    'long' => '9.555373',
    'name' => 'Liechtenstein',
  ),
  'LK' => 
  array (
    'lat' => '7.873054',
    'long' => '80.771797',
    'name' => 'Sri Lanka',
  ),
  'LR' => 
  array (
    'lat' => '6.428055',
    'long' => '-9.429499',
    'name' => 'Liberia',
  ),
  'LS' => 
  array (
    'lat' => '-29.609988',
    'long' => '28.233608',
    'name' => 'Lesotho',
  ),
  'LT' => 
  array (
    'lat' => '55.169438',
    'long' => '23.881275',
    'name' => 'Lithuania',
  ),
  'LU' => 
  array (
    'lat' => '49.815273',
    'long' => '6.129583',
    'name' => 'Luxembourg',
  ),
  'LV' => 
  array (
    'lat' => '56.879635',
    'long' => '24.603189',
    'name' => 'Latvia',
  ),
  'LY' => 
  array (
    'lat' => '26.3351',
    'long' => '17.228331',
    'name' => 'Libya',
  ),
  'MA' => 
  array (
    'lat' => '31.791702',
    'long' => '-7.09262',
    'name' => 'Morocco',
  ),
  'MC' => 
  array (
    'lat' => '43.750298',
    'long' => '7.412841',
    'name' => 'Monaco',
  ),
  'MD' => 
  array (
    'lat' => '47.411631',
    'long' => '28.369885',
    'name' => 'Moldova',
  ),
  'ME' => 
  array (
    'lat' => '42.708678',
    'long' => '19.37439',
    'name' => 'Montenegro',
  ),
  'MG' => 
  array (
    'lat' => '-18.766947',
    'long' => '46.869107',
    'name' => 'Madagascar',
  ),
  'MH' => 
  array (
    'lat' => '7.131474',
    'long' => '171.184478',
    'name' => 'Marshall Islands',
  ),
  'MK' => 
  array (
    'lat' => '41.608635',
    'long' => '21.745275',
    'name' => 'Macedonia [FYROM]',
  ),
  'ML' => 
  array (
    'lat' => '17.570692',
    'long' => '-3.996166',
    'name' => 'Mali',
  ),
  'MM' => 
  array (
    'lat' => '21.913965',
    'long' => '95.956223',
    'name' => 'Myanmar [Burma]',
  ),
  'MN' => 
  array (
    'lat' => '46.862496',
    'long' => '103.846656',
    'name' => 'Mongolia',
  ),
  'MO' => 
  array (
    'lat' => '22.198745',
    'long' => '113.543873',
    'name' => 'Macau',
  ),
  'MP' => 
  array (
    'lat' => '17.33083',
    'long' => '145.38469',
    'name' => 'Northern Mariana Islands',
  ),
  'MQ' => 
  array (
    'lat' => '14.641528',
    'long' => '-61.024174',
    'name' => 'Martinique',
  ),
  'MR' => 
  array (
    'lat' => '21.00789',
    'long' => '-10.940835',
    'name' => 'Mauritania',
  ),
  'MS' => 
  array (
    'lat' => '16.742498',
    'long' => '-62.187366',
    'name' => 'Montserrat',
  ),
  'MT' => 
  array (
    'lat' => '35.937496',
    'long' => '14.375416',
    'name' => 'Malta',
  ),
  'MU' => 
  array (
    'lat' => '-20.348404',
    'long' => '57.552152',
    'name' => 'Mauritius',
  ),
  'MV' => 
  array (
    'lat' => '3.202778',
    'long' => '73.22068',
    'name' => 'Maldives',
  ),
  'MW' => 
  array (
    'lat' => '-13.254308',
    'long' => '34.301525',
    'name' => 'Malawi',
  ),
  'MX' => 
  array (
    'lat' => '23.634501',
    'long' => '-102.552784',
    'name' => 'Mexico',
  ),
  'MY' => 
  array (
    'lat' => '4.210484',
    'long' => '101.975766',
    'name' => 'Malaysia',
  ),
  'MZ' => 
  array (
    'lat' => '-18.665695',
    'long' => '35.529562',
    'name' => 'Mozambique',
  ),
  'NA' => 
  array (
    'lat' => '-22.95764',
    'long' => '18.49041',
    'name' => 'Namibia',
  ),
  'NC' => 
  array (
    'lat' => '-20.904305',
    'long' => '165.618042',
    'name' => 'New Caledonia',
  ),
  'NE' => 
  array (
    'lat' => '17.607789',
    'long' => '8.081666',
    'name' => 'Niger',
  ),
  'NF' => 
  array (
    'lat' => '-29.040835',
    'long' => '167.954712',
    'name' => 'Norfolk Island',
  ),
  'NG' => 
  array (
    'lat' => '9.081999',
    'long' => '8.675277',
    'name' => 'Nigeria',
  ),
  'NI' => 
  array (
    'lat' => '12.865416',
    'long' => '-85.207229',
    'name' => 'Nicaragua',
  ),
  'NL' => 
  array (
    'lat' => '52.132633',
    'long' => '5.291266',
    'name' => 'Netherlands',
  ),
  'NO' => 
  array (
    'lat' => '60.472024',
    'long' => '8.468946',
    'name' => 'Norway',
  ),
  'NP' => 
  array (
    'lat' => '28.394857',
    'long' => '84.124008',
    'name' => 'Nepal',
  ),
  'NR' => 
  array (
    'lat' => '-0.522778',
    'long' => '166.931503',
    'name' => 'Nauru',
  ),
  'NU' => 
  array (
    'lat' => '-19.054445',
    'long' => '-169.867233',
    'name' => 'Niue',
  ),
  'NZ' => 
  array (
    'lat' => '-40.900557',
    'long' => '174.885971',
    'name' => 'New Zealand',
  ),
  'OM' => 
  array (
    'lat' => '21.512583',
    'long' => '55.923255',
    'name' => 'Oman',
  ),
  'PA' => 
  array (
    'lat' => '8.537981',
    'long' => '-80.782127',
    'name' => 'Panama',
  ),
  'PE' => 
  array (
    'lat' => '-9.189967',
    'long' => '-75.015152',
    'name' => 'Peru',
  ),
  'PF' => 
  array (
    'lat' => '-17.679742',
    'long' => '-149.406843',
    'name' => 'French Polynesia',
  ),
  'PG' => 
  array (
    'lat' => '-6.314993',
    'long' => '143.95555',
    'name' => 'Papua New Guinea',
  ),
  'PH' => 
  array (
    'lat' => '12.879721',
    'long' => '121.774017',
    'name' => 'Philippines',
  ),
  'PK' => 
  array (
    'lat' => '30.375321',
    'long' => '69.345116',
    'name' => 'Pakistan',
  ),
  'PL' => 
  array (
    'lat' => '51.919438',
    'long' => '19.145136',
    'name' => 'Poland',
  ),
  'PM' => 
  array (
    'lat' => '46.941936',
    'long' => '-56.27111',
    'name' => 'Saint Pierre and Miquelon',
  ),
  'PN' => 
  array (
    'lat' => '-24.703615',
    'long' => '-127.439308',
    'name' => 'Pitcairn Islands',
  ),
  'PR' => 
  array (
    'lat' => '18.220833',
    'long' => '-66.590149',
    'name' => 'Puerto Rico',
  ),
  'PS' => 
  array (
    'lat' => '31.952162',
    'long' => '35.233154',
    'name' => 'Palestinian Territories',
  ),
  'PT' => 
  array (
    'lat' => '39.399872',
    'long' => '-8.224454',
    'name' => 'Portugal',
  ),
  'PW' => 
  array (
    'lat' => '7.51498',
    'long' => '134.58252',
    'name' => 'Palau',
  ),
  'PY' => 
  array (
    'lat' => '-23.442503',
    'long' => '-58.443832',
    'name' => 'Paraguay',
  ),
  'QA' => 
  array (
    'lat' => '25.354826',
    'long' => '51.183884',
    'name' => 'Qatar',
  ),
  'RE' => 
  array (
    'lat' => '-21.115141',
    'long' => '55.536384',
    'name' => 'Réunion',
  ),
  'RO' => 
  array (
    'lat' => '45.943161',
    'long' => '24.96676',
    'name' => 'Romania',
  ),
  'RS' => 
  array (
    'lat' => '44.016521',
    'long' => '21.005859',
    'name' => 'Serbia',
  ),
  'RU' => 
  array (
    'lat' => '61.52401',
    'long' => '105.318756',
    'name' => 'Russia',
  ),
  'RW' => 
  array (
    'lat' => '-1.940278',
    'long' => '29.873888',
    'name' => 'Rwanda',
  ),
  'SA' => 
  array (
    'lat' => '23.885942',
    'long' => '45.079162',
    'name' => 'Saudi Arabia',
  ),
  'SB' => 
  array (
    'lat' => '-9.64571',
    'long' => '160.156194',
    'name' => 'Solomon Islands',
  ),
  'SC' => 
  array (
    'lat' => '-4.679574',
    'long' => '55.491977',
    'name' => 'Seychelles',
  ),
  'SD' => 
  array (
    'lat' => '12.862807',
    'long' => '30.217636',
    'name' => 'Sudan',
  ),
  'SE' => 
  array (
    'lat' => '60.128161',
    'long' => '18.643501',
    'name' => 'Sweden',
  ),
  'SG' => 
  array (
    'lat' => '1.352083',
    'long' => '103.819836',
    'name' => 'Singapore',
  ),
  'SH' => 
  array (
    'lat' => '-24.143474',
    'long' => '-10.030696',
    'name' => 'Saint Helena',
  ),
  'SI' => 
  array (
    'lat' => '46.151241',
    'long' => '14.995463',
    'name' => 'Slovenia',
  ),
  'SJ' => 
  array (
    'lat' => '77.553604',
    'long' => '23.670272',
    'name' => 'Svalbard and Jan Mayen',
  ),
  'SK' => 
  array (
    'lat' => '48.669026',
    'long' => '19.699024',
    'name' => 'Slovakia',
  ),
  'SL' => 
  array (
    'lat' => '8.460555',
    'long' => '-11.779889',
    'name' => 'Sierra Leone',
  ),
  'SM' => 
  array (
    'lat' => '43.94236',
    'long' => '12.457777',
    'name' => 'San Marino',
  ),
  'SN' => 
  array (
    'lat' => '14.497401',
    'long' => '-14.452362',
    'name' => 'Senegal',
  ),
  'SO' => 
  array (
    'lat' => '5.152149',
    'long' => '46.199616',
    'name' => 'Somalia',
  ),
  'SR' => 
  array (
    'lat' => '3.919305',
    'long' => '-56.027783',
    'name' => 'Suriname',
  ),
  'ST' => 
  array (
    'lat' => '0.18636',
    'long' => '6.613081',
    'name' => 'São Tomé and Príncipe',
  ),
  'SV' => 
  array (
    'lat' => '13.794185',
    'long' => '-88.89653',
    'name' => 'El Salvador',
  ),
  'SY' => 
  array (
    'lat' => '34.802075',
    'long' => '38.996815',
    'name' => 'Syria',
  ),
  'SZ' => 
  array (
    'lat' => '-26.522503',
    'long' => '31.465866',
    'name' => 'Swaziland',
  ),
  'TC' => 
  array (
    'lat' => '21.694025',
    'long' => '-71.797928',
    'name' => 'Turks and Caicos Islands',
  ),
  'TD' => 
  array (
    'lat' => '15.454166',
    'long' => '18.732207',
    'name' => 'Chad',
  ),
  'TF' => 
  array (
    'lat' => '-49.280366',
    'long' => '69.348557',
    'name' => 'French Southern Territories',
  ),
  'TG' => 
  array (
    'lat' => '8.619543',
    'long' => '0.824782',
    'name' => 'Togo',
  ),
  'TH' => 
  array (
    'lat' => '15.870032',
    'long' => '100.992541',
    'name' => 'Thailand',
  ),
  'TJ' => 
  array (
    'lat' => '38.861034',
    'long' => '71.276093',
    'name' => 'Tajikistan',
  ),
  'TK' => 
  array (
    'lat' => '-8.967363',
    'long' => '-171.855881',
    'name' => 'Tokelau',
  ),
  'TL' => 
  array (
    'lat' => '-8.874217',
    'long' => '125.727539',
    'name' => 'Timor-Leste',
  ),
  'TM' => 
  array (
    'lat' => '38.969719',
    'long' => '59.556278',
    'name' => 'Turkmenistan',
  ),
  'TN' => 
  array (
    'lat' => '33.886917',
    'long' => '9.537499',
    'name' => 'Tunisia',
  ),
  'TO' => 
  array (
    'lat' => '-21.178986',
    'long' => '-175.198242',
    'name' => 'Tonga',
  ),
  'TR' => 
  array (
    'lat' => '38.963745',
    'long' => '35.243322',
    'name' => 'Turkey',
  ),
  'TT' => 
  array (
    'lat' => '10.691803',
    'long' => '-61.222503',
    'name' => 'Trinidad and Tobago',
  ),
  'TV' => 
  array (
    'lat' => '-7.109535',
    'long' => '177.64933',
    'name' => 'Tuvalu',
  ),
  'TW' => 
  array (
    'lat' => '23.69781',
    'long' => '120.960515',
    'name' => 'Taiwan',
  ),
  'TZ' => 
  array (
    'lat' => '-6.369028',
    'long' => '34.888822',
    'name' => 'Tanzania',
  ),
  'UA' => 
  array (
    'lat' => '48.379433',
    'long' => '31.16558',
    'name' => 'Ukraine',
  ),
  'UG' => 
  array (
    'lat' => '1.373333',
    'long' => '32.290275',
    'name' => 'Uganda',
  ),
  'US' => 
  array (
    'lat' => '37.09024',
    'long' => '-95.712891',
    'name' => 'United States',
  ),
  'UY' => 
  array (
    'lat' => '-32.522779',
    'long' => '-55.765835',
    'name' => 'Uruguay',
  ),
  'UZ' => 
  array (
    'lat' => '41.377491',
    'long' => '64.585262',
    'name' => 'Uzbekistan',
  ),
  'VA' => 
  array (
    'lat' => '41.902916',
    'long' => '12.453389',
    'name' => 'Vatican City',
  ),
  'VC' => 
  array (
    'lat' => '12.984305',
    'long' => '-61.287228',
    'name' => 'Saint Vincent and the Grenadines',
  ),
  'VE' => 
  array (
    'lat' => '6.42375',
    'long' => '-66.58973',
    'name' => 'Venezuela',
  ),
  'VG' => 
  array (
    'lat' => '18.420695',
    'long' => '-64.639968',
    'name' => 'British Virgin Islands',
  ),
  'VI' => 
  array (
    'lat' => '18.335765',
    'long' => '-64.896335',
    'name' => 'U.S. Virgin Islands',
  ),
  'VN' => 
  array (
    'lat' => '14.058324',
    'long' => '108.277199',
    'name' => 'Vietnam',
  ),
  'VU' => 
  array (
    'lat' => '-15.376706',
    'long' => '166.959158',
    'name' => 'Vanuatu',
  ),
  'WF' => 
  array (
    'lat' => '-13.768752',
    'long' => '-177.156097',
    'name' => 'Wallis and Futuna',
  ),
  'WS' => 
  array (
    'lat' => '-13.759029',
    'long' => '-172.104629',
    'name' => 'Samoa',
  ),
  'XK' => 
  array (
    'lat' => '42.602636',
    'long' => '20.902977',
    'name' => 'Kosovo',
  ),
  'YE' => 
  array (
    'lat' => '15.552727',
    'long' => '48.516388',
    'name' => 'Yemen',
  ),
  'YT' => 
  array (
    'lat' => '-12.8275',
    'long' => '45.166244',
    'name' => 'Mayotte',
  ),
  'ZA' => 
  array (
    'lat' => '-30.559482',
    'long' => '22.937506',
    'name' => 'South Africa',
  ),
  'ZM' => 
  array (
    'lat' => '-13.133897',
    'long' => '27.849332',
    'name' => 'Zambia',
  ),
  'ZW' => 
  array (
    'lat' => '-19.015438',
    'long' => '29.154857',
    'name' => 'Zimbabwe',
  ),
);

?>
