<?php

/**
* @file
* A light-weight plugin for Smallworld.js
* <div class='smallworld' data-country='' data-lat='' data-long=''></div>
*
* TODO:
*
*  - add functionality for recognizing full country names, ex [smallworld=Canada]
*  - add support for jquery color picker module https://www.drupal.org/project/jquery_colorpicker
*/

include_once("smallworld.filters.php");

/**
* Implement hook_menu().
*/
function smallworld_init() {

  libraries_load("smallworld.js");
  $smallworld_settings = array(
    "smallworld_water" => check_plain(variable_get("smallworld_water", "#b3d1ff")),
    "smallworld_land" => check_plain(variable_get("smallworld_land", "#fff")),
    "smallworld_marker_color" => check_plain(variable_get("smallworld_marker_color", "#333")),
    "smallworld_marker_size" => check_plain(variable_get("smallworld_marker_size", 5)),
    "smallworld_center_long" => check_plain(variable_get("smallworld_center_long", 0)),
    "smallworld_center_lat" => check_plain(variable_get("smallworld_center_lat", 0)),
  );

  drupal_add_js(array('smallworld_drupal' => $smallworld_settings),'setting');
  drupal_add_js(drupal_get_path('module', "smallworld")."/js/smallworld.drupal.js");
  drupal_add_css(drupal_get_path('module','smallworld')."/css/smallworld.css");

}

/**
* Implement hook_permission().
*/
function smallworld_permission() {
  return array(
    'administer smallworld' => array(
      'title' => t('Administer Smallworld configuration'),
      'description' => t('Setup basic configuration for Smallworld.'),
    ),
  );
}

/**
* Implement hook_menu().
*/
function smallworld_menu() {

  $items = array();

  $items['admin/config/media/smallworld'] = array(
    'title' => 'SmallWorld.js',
    'description' => 'Configure settings for Smallworld.js module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smallworld_admin_form'),
    'access arguments' => array('administer smallworld'),
    'file' => 'smallworld.admin.inc',
  );

  return $items;

}

/**
 * Implements hook_libraries_info().
 */
function smallworld_libraries_info() {

  $libraries['smallworld.js'] = array(
    'name' => 'SmallWorld.js',
    'vendor url' => 'http://mikefowler.me/smallworld.js/',
    'download url' => 'https://github.com/mikefowler/smallworld.js',
    'version' => '1.0', //no version actually defined in code
    'files' => array(
      'js' => array('src/smallworld.js'),
    ),
  );

  return $libraries;
}

/**
 * Outputs smallworld div with lookup for country code 
 */
function smallworld_output($country = "US") { 

  strtoupper($country); 

  include_once(drupal_get_path("module","smallworld")."/smallworld.data.inc");

  global $smallworld_lookup;

  return _smallworld_output_div($smallworld_lookup[$country]["lat"], $smallworld_lookup[$country]["long"]);

} // end smallworld_output

/**
 * Shared output of smallworld_div 
 */
function _smallworld_output_div($lat ="45", $long="-110") { 

  $smallworld_map_class = check_plain(variable_get("smallworld_map_class", "map"));

  return "<div class='smallworld $smallworld_map_class' data-lat='".$lat."' data-long='".$long."'></div>";

} // end _smallworld_output_div
