<?php

/**
* @file
* A light-weight plugin for Smallworld.js
* <div class='smallworld' data-country='' data-lat='' data-long=''></div>
*/

/**
* Implement hook_menu().
*/
function smallworld_init() {

  libraries_load("smallworld.js");
  $smallworld_settings = array(
    "smallworld_water" => check_plain(variable_get("smallworld_water", "#b3d1ff")),
    "smallworld_land" => check_plain(variable_get("smallworld_land", "#fff")),
    "smallworld_marker_color" => check_plain(variable_get("smallworld_marker_color", "#333")),
    "smallworld_marker_size" => check_plain(variable_get("smallworld_marker_size", 5)),
  );

  drupal_add_js(array('smallworld_drupal' => $smallworld_settings),'setting');
  drupal_add_js(drupal_get_path('module', "smallworld")."/js/smallworld.drupal.js");

}

/**
* Implement hook_permission().
*/
function smallworld_permission() {
  return array(
    'administer smallworld' => array(
      'title' => t('Administer Smallworld configuration'),
      'description' => t('Setup basic configuration for Smallworld.'),
    ),
  );
}

/**
* Implement hook_menu().
*/
function smallworld_menu() {

  $items = array();

  $items['admin/config/media/smallworld'] = array(
    'title' => 'SmallWorld.js',
    'description' => 'Configure settings for Smallworld.js module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smallworld_admin_form'),
    'access arguments' => array('administer smallworld'),
    'file' => 'smallworld.admin.inc',
  );

  return $items;

}

/**
 * Implements hook_libraries_info().
 */
function smallworld_libraries_info() {

  $libraries['smallworld.js'] = array(
    'name' => 'SmallWorld.js',
    'vendor url' => 'http://mikefowler.me/smallworld.js/',
    'download url' => 'https://github.com/mikefowler/smallworld.js',
    'version' => '1.0', //no version actually defined in code
    'files' => array(
      'js' => array('src/smallworld.js'),
      //'js' => array('src/smallworld.jquery.js'),
    ),
  );

  return $libraries;
}
